name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Testing Requirements
        run: sudo pip install -r requirements-test.txt

      - name: Run Unit test for investment app
        run: |
          python manage.py test
